server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    password: ${MYSQL_PASSWORD:root}
    url: jdbc:mysql://${HOST:localhost:3306}/${MYSQL_DATABASE:auth}?useSSL=false
    username: ${MYSQL_USERNAME:root}

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  mail:
    host: localhost
    port: 1025
    username: demo
    password: demo

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
